In [1]:
2 ** 1000

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

In [2]:
import numpy as np

In [8]:
np.int64(2) ** 1000

0

In [11]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [12]:
len(arr)

3

In [14]:
arr[1]

2

In [15]:
type(arr[1])

numpy.int64

In [17]:
arr32 = np.array([1,2,3], dtype=np.int32)
arr32

array([1, 2, 3], dtype=int32)

In [18]:
arr * arr

array([1, 4, 9])

In [19]:
v1 = np.random.rand(1000000)
v2 = np.random.rand(1000000)

In [20]:
%time v1 * v2

CPU times: user 3.56 ms, sys: 3.6 ms, total: 7.16 ms
Wall time: 5.8 ms


array([  4.63878825e-05,   2.06742572e-01,   1.15935691e-01, ...,
         1.05497187e-01,   6.23885265e-02,   2.18231352e-01])

In [21]:
np.dot(arr, arr)

14

In [22]:
arr @ arr

14

In [25]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
v = np.arange(12)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
v.reshape([4,3])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
mat = np.arange(12).reshape(4,3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
mat.shape

(4, 3)

In [31]:
mat2 = mat.reshape([3,4])
mat2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
mat[1,2] = 17
mat2

array([[ 0,  1,  2,  3],
       [ 4, 17,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
mat.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2, 17,  8, 11]])