In [1]:
2 ** 1000

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

In [2]:
import numpy as np

In [3]:
np.int64(2) ** 1000

0

In [4]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
len(arr)

3

In [6]:
arr[1]

2

In [7]:
type(arr[1])

numpy.int64

In [8]:
arr32 = np.array([1,2,3], dtype=np.int32)
arr32

array([1, 2, 3], dtype=int32)

In [9]:
arr * arr

array([1, 4, 9])

In [10]:
v1 = np.random.rand(1000000)
v2 = np.random.rand(1000000)

In [11]:
%time v1 * v2

CPU times: user 3.55 ms, sys: 3.69 ms, total: 7.24 ms
Wall time: 6.49 ms


array([ 0.15874673,  0.05613919,  0.00797691, ...,  0.29532627,
        0.46362378,  0.44074579])

In [12]:
np.dot(arr, arr)

14

In [13]:
arr @ arr

14

In [14]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
v = np.arange(12)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
v.reshape([4,3])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
mat = np.arange(12).reshape(4,3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
mat.shape

(4, 3)

In [19]:
mat2 = mat.reshape([3,4])
mat2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
mat[1,2] = 17
mat2

array([[ 0,  1,  2,  3],
       [ 4, 17,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
mat.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2, 17,  8, 11]])

In [22]:
nums = [1,2,3,4,5]
nums

[1, 2, 3, 4, 5]

In [23]:
nums[2:4]

[3, 4]

In [24]:
v = np.arange(1,6)
v[2:4]

array([3, 4])

In [25]:
arr = np.arange(12).reshape([3,4])
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
arr[0]

array([0, 1, 2, 3])

In [27]:
arr[1,1]

5

In [28]:
arr[:,1]

array([1, 5, 9])

In [29]:
arr[1,:]

array([4, 5, 6, 7])

In [30]:
arr[:,1].reshape([3,1])

array([[1],
       [5],
       [9]])

In [31]:
arr[1:, 2:]

array([[ 6,  7],
       [10, 11]])

In [32]:
arr[1:, 2:] = 7
arr

array([[0, 1, 2, 3],
       [4, 5, 7, 7],
       [8, 9, 7, 7]])